spring:
  datasource:
    url: jdbc:postgresql://localhost/diplomdb
    username: oxyt
    password: 123
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

upload:
  path: /C:/Users/nikki/Documents/uploads